#include "terrain/field_codegen.h"
#include <charconv>
#include <sstream>

namespace ve {
namespace {

// GLSL identifiers cannot contain '.', so "sector.height" becomes "sector_height" both in
// the declaration and at every use site inside a stage body.
std::string ident(const std::string &name) {
	std::string s = name;
	for (char &c : s) if (c == '.') c = '_';
	return s;
}

// Resource type name -> GLSL sampler declaration. Sector resources are ARRAYS: the layer is
// the sector slot, reached through the sector_map indirection, because eval_field() is
// called at arbitrary points that may lie outside the brick being generated.
const char *sampler_type(const std::string &t) {
	if (t == "texture2d_r32f" || t == "texture2d_rg16f" || t == "texture2d_rgba16f")
		return "sampler2DArray";
	if (t == "texture3d_r8" || t == "texture3d_r32f") return "sampler3D";
	return "sampler2DArray";
}

// Numeric ostream insertion consults libstdc++'s locale facets. A GDExtension that embeds
// the static C++ runtime cannot safely share those process-global facets with Godot's own
// runtime, so format numbers with the locale-free to_chars API before appending them.
std::string uint_text(uint64_t value) {
	char buf[32];
	const auto result = std::to_chars(buf, buf + sizeof(buf), value);
	return result.ec == std::errc{} ? std::string(buf, result.ptr) : std::string();
}

std::string float_text(float value) {
	char buf[32];
	const auto result = std::to_chars(buf, buf + sizeof(buf), value,
			std::chars_format::general, 6);
	return result.ec == std::errc{} ? std::string(buf, result.ptr) : std::string();
}

} // namespace

std::string generate_field_glslh(const ResolvedPipeline &p, const std::string &prelude) {
	std::ostringstream o;
	o << "// GENERATED by ve::generate_field_glslh -- do not edit.\n"
	  << "// Pipeline hash: " << uint_text(p.hash) << "\n"
	  << "// Lipschitz bound: " << float_text(p.lipschitz) << "\n"
	  << "// CPU-exact: " << (p.cpu_exact ? "yes" : "no") << "\n\n";

	o << "struct FieldCtx {\n";
	for (const ResolvedChannel &c : p.channels)
		o << "\t" << channel_glsl_type(c.type) << " " << c.name << ";\n";
	o << "};\n\n";

	// The world seed as a domain shift (terrain/seed_offset.h). Declared even at zero so every
	// includer compiles against one shape: leaf_trees.comp.glsl moves its tree records back
	// to world space by it.
	o << "const vec3 VE_FIELD_OFFSET = vec3(" << float_text(float(p.field_offset_x)) << ", 0.0, "
	  << float_text(float(p.field_offset_z)) << ");\n\n";

	o << "layout(set = 1, binding = 0, std140) uniform FieldParams {\n";
	if (p.params.empty()) {
		o << "\tvec4 _unused;\n";
	} else {
		for (const ParamDecl &pm : p.params)
			o << "\t" << channel_glsl_type(pm.type) << " " << ident(pm.name) << ";\n";
	}
	o << "} P;\n\n";

	// Bound even when empty so every field-consuming pass binds set 1 unconditionally and
	// the binding code has no special case. Plan B fills it.
	o << "layout(set = 1, binding = 1, std430) readonly buffer SectorMap {\n"
	  << "\tint slot[];\n"
	  << "} sector_map;\n\n";

	for (size_t i = 0; i < p.resources.size(); i++) {
		o << "layout(set = 1, binding = " << uint_text(2 + i) << ") uniform "
		  << sampler_type(p.resources[i].type) << " " << ident(p.resources[i].name) << ";\n"
		  << "const float " << ident(p.resources[i].name) << "_FALLBACK = "
		  << float_text(p.resources[i].fallback) << ";\n";
	}
	if (!p.resources.empty()) o << "\n";

	for (const StageManifest &s : p.stages) o << s.body << "\n";
	// The bake shader's entry (shaders/sector_bake.comp.glsl). Emitted only when a map stage
	// exists, so every other pipeline's source stays byte-identical.
	if (p.map_stage >= 0)
		o << "#define VE_SECTOR_MAP 1\nvec2 ve_sector_map(vec2 xz) { return stage_"
		  << p.stages[size_t(p.map_stage)].name << "(xz); }\n\n";

	o << "void eval_base_field(vec3 p, out float sdf, out uint mat) {\n"
	  << "\tFieldCtx ctx;\n";
	for (const ResolvedChannel &c : p.channels) {
		if (c.name == "p") { o << "\tctx.p = p + VE_FIELD_OFFSET;\n"; continue; }
		o << "\tctx." << c.name << " = " << channel_glsl_type(c.type) << "(0);\n";
	}
	for (const StageManifest &s : p.stages)
		if (s.kind == StageKind::kField) o << "\tstage_" << s.name << "(ctx);\n";
	o << "\tsdf = ctx.sdf;\n\tmat = ctx.material;\n}\n\n";

	o << prelude;
	return o.str();
}

} // namespace ve
