#include "terrain/field_codegen.h"
#include <sstream>

namespace ve {
namespace {

// GLSL identifiers cannot contain '.', so "sector.height" becomes "sector_height" both in
// the declaration and at every use site inside a stage body.
std::string ident(const std::string &name) {
	std::string s = name;
	for (char &c : s) if (c == '.') c = '_';
	return s;
}

// Resource type name -> GLSL sampler declaration. Sector resources are ARRAYS: the layer is
// the sector slot, reached through the sector_map indirection, because eval_field() is
// called at arbitrary points that may lie outside the brick being generated.
const char *sampler_type(const std::string &t) {
	if (t == "texture2d_r32f" || t == "texture2d_rg16f" || t == "texture2d_rgba16f")
		return "sampler2DArray";
	if (t == "texture3d_r8" || t == "texture3d_r32f") return "sampler3D";
	return "sampler2DArray";
}

} // namespace

std::string generate_field_glslh(const ResolvedPipeline &p, const std::string &prelude) {
	std::ostringstream o;
	o << "// GENERATED by ve::generate_field_glslh -- do not edit.\n"
	  << "// Pipeline hash: " << p.hash << "\n"
	  << "// Lipschitz bound: " << p.lipschitz << "\n"
	  << "// CPU-exact: " << (p.cpu_exact ? "yes" : "no") << "\n\n";

	o << "struct FieldCtx {\n";
	for (const ResolvedChannel &c : p.channels)
		o << "\t" << channel_glsl_type(c.type) << " " << c.name << ";\n";
	o << "};\n\n";

	o << "layout(set = 1, binding = 0, std140) uniform FieldParams {\n";
	if (p.params.empty()) {
		o << "\tvec4 _unused;\n";
	} else {
		for (const ParamDecl &pm : p.params)
			o << "\t" << channel_glsl_type(pm.type) << " " << ident(pm.name) << ";\n";
	}
	o << "} P;\n\n";

	// Bound even when empty so every field-consuming pass binds set 1 unconditionally and
	// the binding code has no special case. Plan B fills it.
	o << "layout(set = 1, binding = 1, std430) readonly buffer SectorMap {\n"
	  << "\tint slot[];\n"
	  << "} sector_map;\n\n";

	for (size_t i = 0; i < p.resources.size(); i++) {
		o << "layout(set = 1, binding = " << (2 + i) << ") uniform "
		  << sampler_type(p.resources[i].type) << " " << ident(p.resources[i].name) << ";\n"
		  << "const float " << ident(p.resources[i].name) << "_FALLBACK = "
		  << p.resources[i].fallback << ";\n";
	}
	if (!p.resources.empty()) o << "\n";

	for (const StageManifest &s : p.stages) o << s.body << "\n";

	o << "void eval_base_field(vec3 p, out float sdf, out uint mat) {\n"
	  << "\tFieldCtx ctx;\n";
	for (const ResolvedChannel &c : p.channels) {
		if (c.name == "p") { o << "\tctx.p = p;\n"; continue; }
		o << "\tctx." << c.name << " = " << channel_glsl_type(c.type) << "(0);\n";
	}
	for (const StageManifest &s : p.stages) o << "\tstage_" << s.name << "(ctx);\n";
	o << "\tsdf = ctx.sdf;\n\tmat = ctx.material;\n}\n\n";

	o << prelude;
	return o.str();
}

} // namespace ve
